# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56bffff48e5e2a87a35ff96589b0e8680ac77c3cabc966c0274e30b005a513a1e5f3d16d55f9e2995213c9754010146534a09852d7c2d1ad7468290fc3f08ebf

test:
  secret_key_base: a625cf8558f48d7bca40ddda1603c905426a33a00cbb03090a06ab3c0b0f351995625df3e4d7cdd5afc8e38c1b53305894e1cb3df9f9021c79daef489f78612f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
